name: CI

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

jobs:
  build_web:
    runs-on: ubuntu-latest
    environment: ci
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js lts/jod
        uses: actions/setup-node@v4
        with:
          node-version: lts/jod
          cache: pnpm

      - name: Install node modules
        run: pnpm install --frozen-lockfile

      - name: Build static pages
        env:
          VITE_SRCDS_SERVER_ADDRESS: ${{ vars.VITE_SRCDS_SERVER_ADDRESS }}
          VITE_SRCDS_SERVER_NAME: ${{ vars.VITE_SRCDS_SERVER_NAME }}
          VITE_SRCDS_SERVER_PORT: ${{ vars.VITE_SRCDS_SERVER_PORT }}
          VITE_SRCDS_SERVER_PROVIDER: ${{ vars.VITE_SRCDS_SERVER_PROVIDER }}
        run: |
          pnpm build

      - name: Test node project
        env:
          VITE_SRCDS_SERVER_ADDRESS: ${{ vars.VITE_SRCDS_SERVER_ADDRESS }}
          VITE_SRCDS_SERVER_NAME: ${{ vars.VITE_SRCDS_SERVER_NAME }}
          VITE_SRCDS_SERVER_PORT: ${{ vars.VITE_SRCDS_SERVER_PORT }}
          VITE_SRCDS_SERVER_PROVIDER: ${{ vars.VITE_SRCDS_SERVER_PROVIDER }}
        run: |
          pnpm exec playwright install --with-deps
          pnpm test:e2e

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

      - name: Compress built files
        if: startsWith(github.ref, 'refs/tags/')
        run: tar -cJvf dist.tar.xz dist

      - name: Publish new release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: dist.tar.xz
          name: Release ${{ github.ref_name }}

  build_electron:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    environment: ci
    permissions:
      contents: write
    needs:
      - build_web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js lts/jod
        uses: actions/setup-node@v4
        with:
          node-version: lts/jod
          cache: pnpm

      - name: Install node modules
        run: pnpm install --frozen-lockfile

      - name: Build static pages
        env:
          VITE_SRCDS_SERVER_ADDRESS: ${{ vars.VITE_SRCDS_SERVER_ADDRESS }}
          VITE_SRCDS_SERVER_NAME: ${{ vars.VITE_SRCDS_SERVER_NAME }}
          VITE_SRCDS_SERVER_PORT: ${{ vars.VITE_SRCDS_SERVER_PORT }}
          VITE_SRCDS_SERVER_PROVIDER: ${{ vars.VITE_SRCDS_SERVER_PROVIDER }}
        run: |
          pnpm build

      - name: Build electron application
        env:
          VITE_SRCDS_SERVER_ADDRESS: ${{ vars.VITE_SRCDS_SERVER_ADDRESS }}
          VITE_SRCDS_SERVER_NAME: ${{ vars.VITE_SRCDS_SERVER_NAME }}
          VITE_SRCDS_SERVER_PORT: ${{ vars.VITE_SRCDS_SERVER_PORT }}
          VITE_SRCDS_SERVER_PROVIDER: ${{ vars.VITE_SRCDS_SERVER_PROVIDER }}
        if: startsWith(github.ref, 'refs/tags/') == false
        run: |
          pnpm make

      - name: Build and publish electron application
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_SRCDS_SERVER_ADDRESS: ${{ vars.VITE_SRCDS_SERVER_ADDRESS }}
          VITE_SRCDS_SERVER_NAME: ${{ vars.VITE_SRCDS_SERVER_NAME }}
          VITE_SRCDS_SERVER_PORT: ${{ vars.VITE_SRCDS_SERVER_PORT }}
          VITE_SRCDS_SERVER_PROVIDER: ${{ vars.VITE_SRCDS_SERVER_PROVIDER }}
        run: |
          pnpm run publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: out-${{ matrix.os }}
          path: out
